visualizaciondatos/app/urls.py
"""Urls app."""
from django.urls import path
from .views import (indexPage,
                    food_group,
                    global_map,)

app_name = 'app'

urlpatterns = [

    path("", indexPage, name="index"),
    path("globalmap", global_map, name="global-map"),
    path("foodgroup", food_group, name="food-group"),
]

visualizaciondatos/visualizaciondatos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

visualizaciondatos/app/models.py
from django.db import models

# Create your models here.

visualizaciondatos/app/views.py
from django.shortcuts import render
import app.urls as urls
import app.graphs as graphs


TEMPLATE_DIR_APP = '/app/templates/app/'

# Create your views here.
def indexPage(request):
    context = {}
    # graphs.open_file()
    get_param = request.GET.get('map')
    context["type_map"] = ""
    if get_param == "Obesity":
        file_name = graphs.map_obesity(template_dir=TEMPLATE_DIR_APP)
        # the filename get from graphs.py
        context["type_map"] = 'app/' + file_name
        
    elif get_param == "Undernourished":
        file_name = graphs.map_desnutrition(template_dir=TEMPLATE_DIR_APP)
        # the filename get from graphs.py
        context["type_map"] = 'app/' + file_name

    elif get_param == "USDA-country":
        file_name = graphs.barplot_tipo_alimentacion(template_dir=TEMPLATE_DIR_APP,
                                                     column="Country")
        context["type_map"] = 'app/' + file_name

    elif get_param == "USDA-continent":
        file_name = graphs.barplot_tipo_alimentacion(template_dir=TEMPLATE_DIR_APP,
                                                     column="Continent")
        context["type_map"] = 'app/' + file_name

    elif get_param == "alcohol":
        file_name = graphs.sunburst_alcohol(template_dir=TEMPLATE_DIR_APP)
        context["type_map"] = 'app/' + file_name

    return render(request, 'app/index.html', context)



def global_map(request):
    context = {}
    get_param = request.GET.get('type')
    template = "app/maps.html"
    
    if get_param == "Obesity":
        file_name = graphs.map_obesity(template_dir=TEMPLATE_DIR_APP)
        # the filename get from graphs.py
        context["type_map"] = 'app/' + file_name
        
    elif get_param == "Undernourished":
        file_name = graphs.map_desnutrition(template_dir=TEMPLATE_DIR_APP)
        # the filename get from graphs.py
        context["type_map"] = 'app/' + file_name
    
    return render(request, template, context)


def food_group(request):
    get_param = request.GET.get('type')
    context = {}
    list_filter = request.GET.get("values", None)
    
    
    if get_param == "USDA-country":
        countries = list(graphs.get_all_countries())
        context["list_item"] = countries
        # list_filter = request.GET.get("values")
        column = "Country"
        context["tipo"] = "por país"
    elif get_param == "USDA-continent":
        continent = list(graphs.get_all_continent())
        context["list_item"] = continent
        # list_filter = request.GET.get("values")
        column = "Continent"
        context["tipo"] = "por continente"

    if list_filter:
        list_filter = list_filter.split(",")

    if get_param == "alcohol":
        countries = list(graphs.get_all_countries())
        context["list_item"] = countries
        context["tipo"] = "por país"
        # list_filter = request.GET.get("values")
        
        file_name = graphs.sunburst_alcohol(template_dir=TEMPLATE_DIR_APP,
                                            countries=list_filter)
        context["type_graph"] = 'app/' + file_name
    else:
        file_name = graphs.barplot_tipo_alimentacion(template_dir=TEMPLATE_DIR_APP,
                                                     column=column,
                                                     countries=list_filter)
    context["type_graph"] = 'app/' + file_name
    context["get_param"] = get_param
    
    # print(a)
    return render(request, 'app/food_group.html', context)

visualizaciondatos/app/templates/app/by_select.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Example</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="component-chosen.css" rel="stylesheet">
</head>

<body>

 
  <div class="col-xs-12 col-md-6 mb-5">
    <label>Multiple:</label>
    <select id="multiple" class="form-control form-control-chosen" data-placeholder="Please select..." multiple>
      <option></option>
      <option selected>Option One</option>
      <option>Option Two</option>
      <option selected>Option Three is a very very very very very very very very very very long text</option>
      <option>Option Four</option>
      <option>Option Five</option>
      <option>Option Six</option>
      <option>Option Seven</option>
      <option>Option Eight</option>
    </select>
  </div>x


  <a id="submit-b" class="btn btn-primary" href="#" role="button">Link</a>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.6/chosen.jquery.min.js"></script>  
  <script type="text/javascript">
$('.form-control-chosen').chosen({
  allow_single_deselect: true,
  width: '100%'
});
$('.form-control-chosen-required').chosen({
  allow_single_deselect: false,
  width: '100%'
});
$('.form-control-chosen-search-threshold-100').chosen({
  allow_single_deselect: true,
  disable_search_threshold: 100,
  width: '100%'
});
$('.form-control-chosen-optgroup').chosen({
  width: '100%'
});

$(function() {
  $('[title="clickable_optgroup"]').addClass('chosen-container-optgroup-clickable');
});
$(document).on('click', '[title="clickable_optgroup"] .group-result', function() {
  var unselected = $(this).nextUntil('.group-result').not('.result-selected');
  if(unselected.length) {
    unselected.trigger('mouseup');
  } else {
    $(this).nextUntil('.group-result').each(function() {
      $('a.search-choice-close[data-option-array-index="' + $(this).data('option-array-index') + '"]').trigger('click');
    });
  }
});
$('#is_valid_chosen').addClass('is-valid');
$('#is_invalid_chosen').addClass('is-invalid');
  </script>


  
  <script>
    $("#submit-b").on("click", function(){
	alert("Hola");
	let multiple = $("#multiple").val();
	console.log(multiple);
	text = "";
	multiple.forEach(get_item);
	console.log(text);
	text = text.slice(0, -1)
	window.location.href = '?country='+text;

	function get_item(item){
	    text = text + item + ",";
	}
    })
  </script>
  

  
</body>

visualizaciondatos/app/templates/app/food_group.html
{% extends 'app/index.html' %}
{% load static %}

{% block other_head %}
  <link href="{% static 'app/chosen/component-chosen.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<p></p> 
  <div class="col-xs-12 col-md-6 mb-5">
    <label>Filtro Múltiple {{ tipo }}:</label>
    <select id="multiple" class="form-control form-control-chosen" data-placeholder="Seleccione uno o más..." multiple>

      {% for item in list_item %}
           <option>{{ item }}</option>
      {% endfor %}
    </select>
  </div>

  <a id="submit-b" class="btn btn-primary" href="#" role="button">Filtrar</a>

<div id="graph-food">
 {% include type_graph %}
</div>
  
{% endblock %}

{% block other_javascript %}
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.6/chosen.jquery.min.js"></script>  
  <script type="text/javascript">
    $('.form-control-chosen').chosen({
	allow_single_deselect: true,
	width: '100%'
    });
    $('.form-control-chosen-required').chosen({
	allow_single_deselect: false,
	width: '100%'
    });
    $('.form-control-chosen-search-threshold-100').chosen({
	allow_single_deselect: true,
	disable_search_threshold: 100,
	width: '100%'
    });
    $('.form-control-chosen-optgroup').chosen({
	width: '100%'
    });

    $(function() {
	$('[title="clickable_optgroup"]').addClass('chosen-container-optgroup-clickable');
    });
    $(document).on('click', '[title="clickable_optgroup"] .group-result', function() {
	var unselected = $(this).nextUntil('.group-result').not('.result-selected');
	if(unselected.length) {
	    unselected.trigger('mouseup');
	} else {
	    $(this).nextUntil('.group-result').each(function() {
		$('a.search-choice-close[data-option-array-index="' + $(this).data('option-array-index') + '"]').trigger('click');
	    });
	}
    });
    $('#is_valid_chosen').addClass('is-valid');
    $('#is_invalid_chosen').addClass('is-invalid');
  </script>


  <script>
    $("#submit-b").on("click", function(){
	let multiple = $("#multiple").val();
	console.log(multiple);
	text = "";
	multiple.forEach(get_item);
	console.log(text);
	text = text.slice(0, -1);

	jQuery.get("foodgroup",
		   {values: text,
		    type: "{{ get_param }}"},
		   
		   function(data){
		       var doc = $(data);
		       var content = doc.find("#graph-food")
		       $("#graph-food").empty();
		       $("#graph-food").html(content);
		   });

	function get_item(item){
	    text = text + item + ",";
	}
    })
  </script>
 
{% endblock %}

visualizaciondatos/app/templates/app/index.html
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block other_head %}{% endblock %}
</head>
<div class="container-fluid">

    <nav class="navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Visualización de Datos - PEC2
        </a>     
    </nav>

    <div class="page-header">
        <h2>Visualización de Datos SARS-CoV2 o COVID-19 en relación al tipo de Alimentación</h2>
        <h6>Por: Fabio Durán-Verdugo</h6>
      </div>

      <div class="alert alert-info" role="alert">
        <strong>Seleccione</strong> un tipo de Visualización.
    </div>

    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">Tipo Mapa            <p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:global-map' %}?type=Obesity">Obesidad
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="radio"  value="{% url 'app:global-map' %}?type=Undernourished">Desnutrición
                </label>
              </div>
        
        </li>

        <li class="list-group-item">Tipo Barplot - Grupo de alimento<p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=USDA-continent">Continente
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=USDA-country">País
                </label>
              </div>
        
        </li>

        <li class="list-group-item">Tipo Sunburst - Relación Alcohol<p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=alcohol">Alcohol
                </label>
              </div>
        
        </li>
      </ul>


    {% block content %}
    <p></p>
<div class="card">
  <h3 class="card-header">Introducción</h3>
  <div class="card-body">
    <p class="text-justify">
      El siguiente trabajo muestra la visualización de datos de diferentes tipos de
alimentos en su consumo y además de la tasa de obesidad y desnutrición
de la población mundial. Incluye un recuento de casos de SARS-CoV2 o
      COVID-19 para muchos lugares del mundo.
    </p>
    <p class="text-justify">
      El Centro de Política y Promoción de la Nutrición del USDA recomienda
una pauta de ingesta de dieta diaria muy simple: 30 % de granos, 40 % de
verduras, 10 % de frutas y 20 % de proteína y que el autor de este conjun-
to de datos, Maria Ren (https://www.kaggle.com/mariaren), dada esta pauta se realiza la pregunta ¿estamos
realmente comiendo en el estilo de alimentación saludable recomendado por
estas divisiones de alimentos y saldos?
    </p>
    <p class="text-justify">
De cierto modo es posible apreciar ciertas tendencias a responder esta pre-
gunta que apunta a un estilo de alimentación saludable, pero en conjunto
se han incluido de cifras de contagios confirmados, recuperados, muertos y
activos de SARS-CoV2 (coronavirus), por lo hace suponer una nueva arista
que aportaría desde otro tipo de ciencia a combatir el virus.
Otro beneficio visual es que es factible poder captar y comparar a través de
gráficos son los estilos de alimentación o dietas que llevan los distintos países,
incluyendo también a los continentes en donde se encuentran ubicados.
    </p>

    <p class="text-justify">
El dataset trabajado se encuentra en la siguiente url: https://www.kaggle.
com/mariaren/covid19-healthy-diet-dataset?select=Food_Supply_kcal_
Data.csv, datasets licenciados con creative common by-sa 2 , y representa a
los porcentajes de ingesta energética (kcal) de diferentes tipos de alimentos
en países de todo el mundo. El último par de columnas también incluye
recuentos de casos de obesidad, desnutrición y COVID-19 como porcentajes
de la población total para fines de comparación.
    </p>
  </div>
</div>
<p></p>

      <div class="alert alert-info" role="alert">
        <strong>Seleccione</strong> un tipo de Visualización.
    </div>

    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">Tipo Mapa            <p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:global-map' %}?type=Obesity">Obesidad
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="radio"  value="{% url 'app:global-map' %}?type=Undernourished">Desnutrición
                </label>
              </div>
        
        </li>

        <li class="list-group-item">Tipo Barplot - Grupo de alimento<p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=USDA-continent">Continente
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=USDA-country">País
                </label>
              </div>
        
        </li>

        <li class="list-group-item">Tipo Sunburst - Relación Alcohol<p></p>      
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="radio"  value="{% url 'app:food-group' %}?type=alcohol">Alcohol
                </label>
              </div>
        
        </li>
      </ul>



    {% endblock %}

    

</div>


{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script type="text/javascript">
    $('input[type=radio][name=radio]').change(function() {

        window.location.href = this.value
        
    });
  </script>
  {% endblock %}

  {% block other_javascript %}{% endblock %}

visualizaciondatos/app/templates/app/maps.html
{% extends "app/index.html" %}
{% block content %}

{% if type_map %}
    {% include  type_map %}
{% endif %}

{% endblock %}